[package]
name = "digit"
version = "0.1.0"
edition = "2021"

[dependencies]
nannou = "0.19.0"
pixel-canvas = "0.2.3"
rand = "0.9.0-beta.3"
serde = { version = "1.0.217", features = ["derive"] }
serde_cbor = "0.11.2"